apiVersion: v1
kind: Template
labels:
  template: neo4j-prometheus-template #${NAMESPACE}-template
message: Your template has been created.
metadata:
  name: neo4j-prometheus-template #${NAMESPACE}-template
objects:

#image stream Prometheus
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${NAME}
    name: ${PROMETHEUS_NAME}
    namespace: ${NAMESPACE}

#build config Prometheus
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${PROMETHEUS_NAME}
    namespace: ${NAMESPACE}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${PROMETHEUS_NAME}:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${SOURCE_REPOSITORY_CONTEXT_DIR_PROMETHEUS}
      git:
        ref: main
        uri: '${SOURCE_REPOSITORY_URL}'
      type: Git
    strategy:
      dockerStrategy:
      #dockerfilePath: neo4j/Dockerfile
      # from:
      #   kind: DockerImage
      #   name: 'mysql:8.0.20'
      type: Docker
    triggers:
      - imageChange:
          lastTriggeredImageID: #>-
          #docker.io/openshift/wildfly-101-centos7@sha256:7775d40f77e22897dc760b76f1656f67ef6bd5561b4d74fbb030b977f61d48e8
        type: ImageChange
      - type: ConfigChange
      - generic:
          secret: 9fdf619e0aea935a
        type: Generic
      - github:
          secret: 43ac13d4078565c4
        type: GitHub

#service
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    #type: LoadBalancer
    ports:
      #prometheus port
      - name: ${PROMETHEUS_NAME}-http
        port: 9090
        protocol: TCP
        targetPort: 9090
    selector:
      deploymentconfig: ${NAME}

#persistent volume
#- apiVersion: v1
#  kind: PersistentVolumeClaim
#  metadata:
#    name: prometheus-pvc
#    labels:
#      app: ${NAME}
#  spec:
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: 1Gi

#deployment
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
          #---------------------
          # prometheus container
          #---------------------
          - image: '${PROMETHEUS_NAME}:latest'
            name: ${PROMETHEUS_NAME}
            ports:
              - containerPort: 9090
                protocol: TCP
            resources: { }
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            #env:
            #  - name: NEO4J_AUTH
            #    value: ${NEO4J_AUTH}
            volumeMounts:
              - mountPath: ${MOUNT_PATH_PROMETHEUS_CONF}
                name: prometheus-conf
              - mountPath: ${MOUNT_PATH_PROMETHEUS_DATA}
                name: prometheus-data
#        initContainers:
#          - name: prometheus-data-permission-fix
#            image: busybox
#            command: [ "sh", "-c", 'chown -R 1000170000 /data/*' ]
#            volumeMounts:
#              - name: prometheus-data
#                mountPath: /data
        volumes:
          #prometheus volumes
          - name: prometheus-conf
          - name: prometheus-data
#            persistentVolumeClaim:
#              claimName: prometheus-pvc
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    #trigget prometheus
    - imageChangeParams:
        automatic: true
        containerNames:
          - ${PROMETHEUS_NAME}
        from:
          kind: ImageStreamTag
          name: '${PROMETHEUS_NAME}:latest'
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange

#parametri
parameters:

#---------------------------------------------------------------------------NAMES

- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: "project-test"

- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  value: "neo4j-prometheus"

- description: The name assigned to Prometheus image stream.
  displayName: Prometheus Image Name
  name: PROMETHEUS_NAME
  value: "prometheus"

#---------------------------------------------------------------------------GIT
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  value: "https://github.com/faber03/ProjectTest.git"

- description: The repository directory subpath of Prometheus Dockerfile.
  displayName: Git Repository subpath
  name: SOURCE_REPOSITORY_CONTEXT_DIR_PROMETHEUS
  value: "/Neo4j/Neo4j-Prometheus/Prometheus"

  #---------------------------------------------------------------------------VOLUMES

- description: Mounth path Prometheus conf.
  displayName: Mounth path Prometheus conf
  name: MOUNT_PATH_PROMETHEUS_CONF
  value: "/path/to/config"

- description: Mounth path Prometheus data.
  displayName: Mounth path Prometheus data
  name: MOUNT_PATH_PROMETHEUS_DATA
  value: "/prometheus/data"

#---------------------------------------------------------------------------ENVIRONMENT