
#image stream
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: hta #${NAME}
  name: hta #${NAME}
  namespace: tesi-delucia #${NAMESPACE}
---
#build config
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hta #${NAME}
  name: hta #${NAME}
  namespace: tesi-delucia #${NAMESPACE}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hta:latest' #'${NAME}:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: '/HorizontalTaskAutoscaler' #${SOURCE_REPOSITORY_CONTEXT_DIR}
    git:
      ref: main
      uri: 'https://github.com/faber03/ProjectTesi.git' #'${SOURCE_REPOSITORY_URL}'
    type: Git
  strategy:
    #dockerStrategy:
    #dockerfilePath: Neo4j/Dockerfile
    # from:
    #   kind: DockerImage
    #   name: 'mysql:8.0.20'
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: #>-
        #docker.io/openshift/wildfly-101-centos7@sha256:7775d40f77e22897dc760b76f1656f67ef6bd5561b4d74fbb030b977f61d48e8
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 9fdf619e0aea935a
      type: Generic
    - github:
        secret: 43ac13d4078565c4
      type: GitHub
---
#deployment
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: hta #${NAME}
  name: hta #${NAME}
  namespace: tesi-delucia #${NAMESPACE}
spec:
  replicas: 1
  selector:
    deploymentconfig: hta #${NAME}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hta #${NAME}
        deploymentconfig: hta #${NAME}
    spec:
      containers:
        #mysql container
        - image: 'hta:latest' #'${NAME}:latest'
          name: hta #${NAME}
#              ports:
#                - containerPort: 7474
#                  protocol: TCP
#                - containerPort: 7687
#                  protocol: TCP
#                - containerPort: 7473
#                  protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: NEO4J_JMX_USERNAME
              value: 'monitor'
            - name: NEO4J_JMX_PASSWORD
              value: 'Neo4j'
            - name: NEO4J_JMX_HOST
              value: 'neo4j.tesi-delucia.svc:32766'
            - name: KAFKA_CONNECT_HOST
              value: 'kafka-connect-neo4j-cp-kafka-connect-neo4j.tesi-delucia.svc:8083'
            - name: KAFKA_CONNECTOR_NAME
              value: 'neo4j-sink'
            - name: LOG_PATH
              value: 'log.txt'
            - name: NEO4J_OLDGEN_MAX
              value: '110000000'
            - name: NEO4J_OLDGEN_MIN
              value: '60000000'
            - name: STABILIZATION_DELAY_MSEC
              value: '30000'
            - name: METRIC_READING_DELAY_MSEC
              value: '5000'
            - name: SCALING_STEP
              value: '1'
            - name: SCALING_MAX
              value: '7'
            - name: SCALING_MIN
              value: '1'
            - name: LIFETIME_SEC
              value: '3600'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - hta #${NAME}
        from:
          kind: ImageStreamTag
          name: 'hta:latest' #${NAME}:latest'
          namespace: tesi-delucia ##${NAMESPACE}
      type: ImageChange
    - type: ConfigChange