apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jmeter-testsuite
  label:
    application: jmeter-testsuite
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: jmeter-testsuite
  name: jmeter-testsuite
  namespace: tesi-delucia
  selfLink: /apis/build.openshift.io/v1/namespaces/tesi/buildconfigs/jmeter-testsuite
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jmeter-testsuite:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: '/JMeter'
    git:
      ref: main
#      uri: 'git remote add origin https://github.com/faber03/JMeter.git'
      uri: 'https://github.com/faber03/ProjectTesi.git'
    type: Git
  strategy:
#    dockerStrategy:
#      from:
#        kind: DockerImage
#        name: 'openjdk:8-jre-slim'
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: #>-
          #docker.io/openshift/wildfly-101-centos7@sha256:dfc66d3681c5a3000a852947f3a3679e72ac016b0823b3e474d420378f555c2d
      type: ImageChange
    - type: ConfigChange
    - generic:
#        secret: ef608792b1f93988
        secret: 9fdf619e0aea935a
      type: Generic
    - github:
#        secret: 7c78239b5fa4ab9d
        secret: 43ac13d4078565c4
      type: GitHub
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
#  annotations:
#  creationTimestamp: '2018-10-03T12:42:15Z'
#  generation: 30
  labels:
    app: jmeter-testsuite
  name: jmeter-testsuite
  namespace: tesi-delucia
#  resourceVersion: '16954484'
#  selfLink: >-
#    /apis/apps.openshift.io/v1/namespaces/tesi/deploymentconfigs/openshift-jee-sample
#  uid: c187bf94-c709-11e8-9de5-fa163ee7bbde
spec:
  replicas: 1
  selector:
    deploymentconfig: jmeter-testsuite
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jmeter-testsuite
        deploymentconfig: jmeter-testsuite
    spec:
      containers:
        - image: jmeter-testsuite:latest
          name: jmeter-testsuite
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jmeter-testsuite
        from:
          kind: ImageStreamTag
          name: 'jmeter-testsuite:latest'
          namespace: tesi
#        lastTriggeredImage: >-
#          docker-registry.default.svc:5000/tesi/openshift-jee-sample@sha256:1b7da0f4bc1212d55174205157a738d46e0f38a33041b9cdf5d4735edfb087dc
      type: ImageChange
    - type: ConfigChange
