kind: ServiceAccount
apiVersion: v1
metadata:
  name: resource-metrics-apiserver
  namespace: tesi-delucia
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: prometheus-adapter-resource
    namespace: tesi-delucia
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config-resource
  namespace: tesi-delucia
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__="nginx_http_requests_total",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
          service: {resource: "service"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-adapter-resource-tls
  labels:
    name: prometheus-adapter-resource
  name: prometheus-adapter-resource
  namespace: tesi-delucia
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
  selector:
    app: prometheus-adapter-resource
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-adapter-resource
  name: prometheus-adapter-resource
  namespace: tesi-delucia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter-resource
  template:
    metadata:
      labels:
        app: prometheus-adapter-resource
      name: prometheus-adapter-resource
    spec:
      #serviceAccountName: resource-metrics-apiserver
      serviceAccountName: resource-metrics-apiserver
      containers:
        - name: prometheus-adapter-resource
          image: directxman12/k8s-prometheus-adapter-amd64
          args:
            - --secure-port=6443
            - --tls-cert-file=/var/run/serving-cert/tls.crt
            - --tls-private-key-file=/var/run/serving-cert/tls.key
            - --logtostderr=true
            #- --prometheus-url=http://prometheus.prom.svc:9090/
            - --prometheus-url=http://prometheus-operated.tesi-delucia.svc:9090/
            - --metrics-relist-interval=1m
            - --v=4
            - --config=/etc/adapter/config.yaml
          ports:
            - containerPort: 6443
          volumeMounts:
            - mountPath: /var/run/serving-cert
              name: volume-serving-cert
              readOnly: true
            - mountPath: /etc/adapter/
              name: config
              readOnly: true
            - mountPath: /tmp
              name: tmp-vol
      volumes:
        - name: volume-serving-cert
          secret:
            secretName: prometheus-adapter-resource-tls
        - name: config
          configMap:
            name: adapter-config-resource
        - name: tmp-vol
          emptyDir: {}