FROM prom/prometheus

#SHELL ["/bin/bash", "-c"]

#USER root

#ADD prometheus.yml /etc/prometheus/
ADD prometheus.yml /path/to/config

#RUN chown 1000170000 /etc/prometheus/queries.active
#RUN chmod 777 /etc/prometheus/queries.active

EXPOSE 9090