kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: neo4j-connector-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    #kind: DeploymentConfig
    kind: Deployment
    #name: neo4j
    name: sample-app2

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: External
  external:
    #metricName: neo4j_neo4j_transaction_active
    metricName: nginx_http_requests_per_second
    targetValue: 70m