kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: APP_TO_SCALE-hpa
  namespace: NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    #kind: DeploymentConfig
    kind: Deployment
    name: APP_TO_SCALE

  minReplicas: MIN_REPLICAS
  maxReplicas: MAX_REPLICAS

  metrics:
    - type: External
      external:
        metricName: neo4j_metric
        targetValue: TARGET_METRICA_VALUE

# NAMESPACE: tesi-delucia
# APP_TO_SCALE: neo4j-connector
# MIN_REPLICAS: 1
# MAX_REPLICAS: 10
# TARGET_METRICA_VALUE: 20m