#deployment
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: neo4j-neo4j-core
  namespace: tesi-delucia
  labels:
    app: neo4j
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      nodeSelector:
        kubernetes.io/hostname: compute3
      initContainers:
        - name: init-plugins
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugins
              mountPath: /plugins
          command:
            - "/bin/sh"
            - "-c"
            - |
              curl -L https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.5.4.0/graph-algorithms-algo-3.5.4.0.jar -O
              cp graph-algorithms-algo-3.5.4.0.jar /plugins/
              curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.4.0.4/apoc-3.4.0.4-all.jar -O
              cp apoc-3.4.0.4-all.jar /plugins/
      containers:
        #----------------
        # neo4j container
        #----------------
        - image: neo4j:3.4.5-enterprise
          name: neo4j
          imagePullPolicy: IfNotPresent
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_AUTH
              value: "neo4j/password"
            - name: NEO4J_dbms_connector_bolt_address
              value: "0.0.0.0:7687"

            - name: NEO4J_metrics_prometheus_enabled  #metrics.prometheus.enabled=true
              value: "true"
            - name: NEO4J_metrics_prometheus_endpoint #metrics.prometheus.endpoint=0.0.0.0:2004
              value: "0.0.0.0:2004"

            - name: NEO4J_metrics_enabled
              value: "true"
            - name: NEO4J_metrics_jmx_enabled
              value: "true"
#
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote=true"
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.port=3637" #3637
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.rmi.port=3001"
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Djava.rmi.server.hostname=127.0.0.1"
#
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.authenticate=false"
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.local.only=false"
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.ssl=false"
#
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.password.file=/var/lib/neo4j/conf/jmx.password"
#            - name: NEO4J_dbms_jvm_additional
#              value: "-Dcom.sun.management.jmxremote.access.file=/var/lib/neo4j/conf/jmx.access"

            - name: NEO4J_dbms_memory_heap_initial__size #lower to start 33M (no prometheus), 40M (con prometheus)
              value: "180M"
            - name: NEO4J_dbms_memory_heap_max__size #64 no, 128 ...
              value: "180M" # value: "64M"
#            - name: NEO4J_dbms_jvm_additional
#              value: "-XX:NewRatio=2" #old = 2/3 di heap, young = 1/3 di heap (l'old è 2 volte la young)
            - name: NEO4J_dbms_jvm_additional
              value: "-XX:+CrashOnOutOfMemoryError -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=32766 -Dcom.Sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=32766 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.password.file=/var/lib/neo4j/conf/jmx.password -Dcom.sun.management.jmxremote.access.file=/var/lib/neo4j/conf/jmx.access -Djava.rmi.server.hostname=127.0.0.1"
              #value: "-XX:+CrashOnOutOfMemoryError -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=32766 -Dcom.Sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=32766 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.password.file=/var/lib/neo4j/conf/jmx.password -Dcom.sun.management.jmxremote.access.file=/var/lib/neo4j/conf/jmx.access"

            - name: NEO4J_dbms_mode
              value: SINGLE

#            - name: AUTH_ENABLED
#              value: "true"
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: "apoc.\\*,algo.\\*"
            - name: NEO4J_apoc_export_file_enabled
              value: "true"
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
#            - containerPort: 7473
#              protocol: TCP
#              name: https
            - containerPort: 2004
              name: metrics
            - containerPort: 32766 #3637 #32766
              name: jmx
          volumeMounts:
            - mountPath: "/data"
              name: datadir
            - mountPath: "/plugins"
              name: plugins
          resources:
            limits: # 1,9 core tetto massimo (limit >= request altrimenti il pod non si avvia) - overbooking
              cpu: 5000m #1900m
            requests: # valore monopolizzato dal pod, indipendentemente dalle risorse reali impiegate
              cpu: 5000m #1900m
      volumes:
        #neo4j volumes
        - name: datadir
          emptyDir: {}
        - name: plugins
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: "neo4j-neo4j-core-0"
  namespace: tesi-delucia
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    statefulset.kubernetes.io/pod-name: "neo4j-neo4j-core-0"
    #app: neo4j
#    statefulset.kubernetes.io/pod-name: "{{ template "neo4j.core.fullname" . }}-0"
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 7474
      targetPort: 7474
      name: broswer
    - protocol: TCP
      nodePort: 32000
      port: 7687
      targetPort: 7687
      name: bolt
#    - protocol: TCP
#      nodePort: 32766
#      port: 32766 #3637
#      targetPort: 32766 #3637
#      name: jmx
---
#service
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: tesi-delucia
  labels:
    app: neo4j
spec:
  ports:
    - name: metrics
      port: 2004
      protocol: TCP
      targetPort: 2004
    - name: jmx
      port: 32766 #3637
      protocol: TCP
      targetPort: 32766 #3637
  selector:
    app: neo4j
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neo4j-metrics
  namespace: tesi-delucia
  labels:
    app: neo4j
spec:
  port:
    targetPort: metrics
  path: /metrics
  to:
    kind: Service
    name: neo4j
    weight: 100
  wildcardPolicy: None
