#service
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: NAMESPACE
  labels:
    app: neo4j
spec:
  ports:
    - name: metrics
      port: 2004
      protocol: TCP
      targetPort: 2004
  selector:
    app: neo4j
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neo4j-metrics
  namespace: NAMESPACE
  labels:
    app: neo4j
spec:
  port:
    targetPort: metrics
  path: /metrics
  to:
    kind: Service
    name: neo4j
    weight: 100
  wildcardPolicy: None