#------------------------------------------------------ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: NAMESPACE
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: APP_TO_MONITOR_NAME
  endpoints:
    - port: APP_TO_MONITOR_PORT
#-----------------------------------------------------------PROMETHEUS
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: NAMESPACE
  name: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: NAMESPACE
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: prometheus
spec:
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
---
#route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: NAMESPACE
spec:
  port:
    targetPort: web
  path:
  to:
    kind: Service
    name: prometheus
    weight: 100
  wildcardPolicy: None

# APP_TO_MONITOR_NAME: neo4j
# APP_TO_MONITOR_PORT: metrics